# Simple workflow for deploying static content to GitHub Pages
name: HTML checker

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
        name: HTML checker
        uses: anishathalye/proof-html@v1
        with:
          directory: ./
          enforce_https: true